# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b0ddef99620e3b597e53c4460fd738e0bd08c67c19996e237993de266f41ada821bc6fee7fe6fb3d5bf060af8e61471e12a120cacd115f9855e2c5e42ebd62

test:
  secret_key_base: 7f3e440b47ca950ef90ac35387662255c1fc14e1fa5fc16137871ef7032f57232a1310a8353b41ae5ee458b3194c66a947e9cd72a050717c70aaba622fd46588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
